### PR TITLE
headless testing

### PR DESCRIPTION
**Pull request by developit**

### CODE REVIEW

**Comment by domenic** [comment]
The logs only show one test run; is this actually doing its magic on both Firefox and Chrome?

**Comment by developit** [comment]
@domenic unfortunately SauceLabs can't run on PRs without exposing access tokens :(

**Comment by domenic** [comment]
Ah right, I remember that problem -_-. I wish there were a better alternative than sauce labs, but oh well!

**Comment by developit** [comment]
finally! see [issue #7](https://pouchdb.com/2014/10/26/10-things-i-learned-from-reading-and-writing-the-pouchdb-source.html) here, which was roughly the cause (`openCursor().then(..)` breaks transactions in some versions of IE11).

Screen Shot 2019-04-28 at 9 06 10 PM

**Pull request merged**
